### PR TITLE
Allow access the server's CA certificate through the API

### PR DESCRIPTION
**Pull request by skateman**
https://github.com/ManageIQ/manageiq/pull/7078

### CODE REVIEW

**Comment by skateman** [comment]
@bdunne I'm not sure how to test this method :(

**Comment by bdunne** [comment]
@skateman we have some tests around a similar method here: https://github.com/ManageIQ/ovirt/blob/master/spec/service_spec.rb#L51-L73

**Comment by bdunne** [comment]
I had some test suggestions which was easiest to put in a PR.  https://github.com/skateman/ovirt/pull/1

Can you add a test case for an unexpected response (not a certificate / server doesn't support this)?

I think we should cache the certificate on the service instance so that future calls do fetch the file again.  What do you think?

**Comment by skateman** [comment]
@bdunne caching fixed, but I don't know how to add that testcase :(

**Comment by bdunne** [comment]
@skateman Right now you're not verifying that you receive a certificate.  You could test the "not a certificate" case by duplicating the current test and changing `cert = blah`.  The "server doesn't support this" test case could raise `RestClient::ResourceNotFound` and take some other action based on that.

**Comment by bdunne** [comment]
@skateman To help move things along, I created https://github.com/skateman/ovirt/pull/2

**Comment by skateman** [comment]
@bdunne thanks

**Pull request merged**
