### PR TITLE
Object#namespace was removed from MoreCoreExtensions by #20

### PR DESCRIPTION
**Pull request by bdunne**
https://github.com/ManageIQ/more_core_extensions/pull/20
fixes https://github.com/ManageIQ/manageiq/issues/6859

### CODE REVIEW

**Comment by bdunne** [comment]
@Fryguy @gmcculloug Please review

**Comment by gmcculloug** [comment]
:+1: Would be nice to have a test for this as well.

**Comment by bdunne** [comment]
@gmcculloug tests added

**Comment by gmcculloug** [comment]
Looks good, thx

**Comment by bdunne** [comment]
Kicking Travis again (with updated .travis.yml this time)

**Comment by bdunne** [comment]
Merging on behalf of @gmcculloug

**Pull request merged**
