### PR TITLE
Remove typo as AUTO_SUSPEND_VM event doesn't exist.

### PR DESCRIPTION
**Pull request by jrafanie**
Note, ruby 2.2 complains if you try to assign the same key to a second
value.

The documentation [1] we used to get this information is wrong [2].

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.2/html-single/Developer_Guide/index.html
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1231345

cc @brandondunne @Fryguy

### CODE REVIEW

**Comment by Fryguy** [comment]
:+1:

**Comment by Fryguy** [comment]
oops sorry...I hate that those two buttons are right next to each other :confounded:

**Comment by Fryguy** [comment]
Can we add Ruby 2.2 to travis?  (Maybe we should just go through all the gems and do this)

**Comment by jrafanie** [comment]
Yes, that's a good idea.

**Comment by kbrock** [comment]
:+1: yay. can you push this?

**Pull request merged**
