### PR TITLE
Add a probe for ovirt using the public key API /engine.ssh.key.txt

### PR DESCRIPTION
**Pull request by jrafanie**
Related to https://github.com/ManageIQ/manageiq/issues/1497

cc @Fryguy @brandondunne

### CODE REVIEW

**Comment by Fryguy** [comment]
LGTM except one minor style issue (equals after password missing a space )

**Comment by jrafanie** [comment]
ok @Fryguy fixed.

**Comment by Fryguy** [comment]
:+1:

I'm holding off a release of ovirt to get more data collection in... Do you need this sooner than later?

**Comment by jrafanie** [comment]
No, I can wait, just wanted to add this now so I can use it later to fix the manageiq discovery code.

**Pull request merged**
