### PR TITLE
Add new 'ca_certs' option

### PR DESCRIPTION
**Pull request by jhernand**
This patch adds a new 'ca_certs' option to the constructor of the
'Service' class. This option is a string containing one or multiple
trusted CA certificates, in PEM format. If given, those certificates
will be used to check the certificate presented by the server.

### CODE REVIEW

**Comment by jhernand** [comment]
@Fryguy please review.

**Comment by jhernand** [comment]
@bdunne can you review and do a new release of the gem when/if this is merged?

**Comment by jhernand** [comment]
@Fryguy thanks. @bdunne can you do the new release of the gem?

**Comment by bdunne** [comment]
Released v0.15.0

**Comment by jhernand** [comment]
@bdunne thanks.

**Comment by jhernand** [comment]
[SSL host verification - finilizing](https://trello.com/c/gtbzw6TQ/121-ssl-host-verification-finilizing)

**Pull request merged**
