### PR TITLE
Support host maintenance actions

### PR DESCRIPTION
**Pull request by masayag**
The patch adds support for host maintenance actions (activate
and deactivate host) to the host power operations.

### CODE REVIEW

**Comment by masayag** [comment]
@miq-bot assign @borod108

**Comment by masayag** [comment]
This PR is required for https://github.com/ManageIQ/manageiq-providers-ovirt/pull/58

**Comment by masayag** [comment]
@bdunne can this be merged ?

**Comment by bdunne** [comment]
@masayag Are these not in the `@operations` hash that would be handled by `method_missing` [here](https://github.com/ManageIQ/ovirt/blob/master/lib/ovirt/base.rb#L258)?

**Comment by masayag** [comment]
@bdunne seems to work fine without this patch. What a lovely sorcery! 

I'm closing this PR since the method_missing covers this as well. Thanks.

**Pull request closed without merging**
