### PR TITLE
Use full_version if available since version is wrong

### PR DESCRIPTION
**Pull request by bdunne**
https://bugzilla.redhat.com/show_bug.cgi?id=1284654

### CODE REVIEW

**Comment by bdunne** [comment]
@gmcculloug Please review

**Comment by gmcculloug** [comment]
@bdunne Looks good.  Needs tests.

**Comment by bdunne** [comment]
@gmcculloug Tests added

**Comment by gmcculloug** [comment]
@bdunne Failing tests: `undefined method 'to_h'` for the Ruby 1.9 and 2.0 environments.

**Comment by gmcculloug** [comment]
Looks good.  Please merge.

**Pull request merged**
