### PR TITLE
Host maintenance

### PR DESCRIPTION
**Pull request by pkliczewski**
There were few maintenance event missing:

USER_VDS_MAINTENANCE_WITHOUT_REASON(620)
VDS_MAINTENANCE_MANUAL_HA(10452)
USER_VDS_MAINTENANCE_MANUAL_HA(10453)

which was unknown by the provider. As a result we do not trigger
refresh and the host status is not updated.

### CODE REVIEW

**Comment by pkliczewski** [comment]
@miq-bot assign @borod108

**Comment by pkliczewski** [comment]
@borod108 @masayag please review

**Comment by masayag** [comment]
@pkliczewski please update the commit message and PR message to include the additional events.

**Comment by pkliczewski** [comment]
@miq-bot  assign @bdunne

**Comment by bdunne** [comment]
Thanks @pkliczewski v0.18.0 is now released with these changes

**Pull request merged**
